language: bash
services: docker

env:
  - VERSION=2.0.11

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="docker.io/vaidik/etcd:${VERSION}${VARIANT:+-${VARIANT}}"

script:
  - |
    (
      set -x
      travis_retry docker build -t "$image" .
      docker run --rm --entrypoint echo "$image" "Hello $hello"
      ~/official-images/test/run.sh "$image"
    )
after_script:
  - docker images
